import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import useAuthStore from '../store/authStore'
import { getJobRecommendations } from '../services/jobService'

const JOBS_PER_PAGE = 6

const Jobs = () => {
  const { isAuthenticated } = useAuthStore()
  const navigate = useNavigate()
  const [jobs, setJobs]       = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError]     = useState('')
  const [page, setPage]       = useState(0)

  useEffect(() => {
    if (!isAuthenticated) navigate('/login')
  }, [isAuthenticated, navigate])

  useEffect(() => {
    const load = async () => {
      try {
        const data = await getJobRecommendations()
        if (data.success) setJobs(data.jobs)
        else setError(data.message)
      } catch (err) {
        const message = err?.response?.data?.message
          || 'Failed to load recommendations. Please try again.'
        setError(message)
      } finally {
        setLoading(false)
      }
    }
    load()
  }, [])

  // ── Pagination logic ──
  const totalPages  = Math.ceil(jobs.length / JOBS_PER_PAGE)
  const visibleJobs = jobs.slice(page * JOBS_PER_PAGE, page * JOBS_PER_PAGE + JOBS_PER_PAGE)

  const goNext = () => {
    if (page < totalPages - 1) setPage(page + 1)
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  const goPrev = () => {
    if (page > 0) setPage(page - 1)
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  // ── Loading ──
  if (loading) {
    return (
      <div
        style={{ minHeight: 'calc(100vh - 57px)' }}
        className="flex flex-col items-center justify-center
                   bg-gradient-to-br from-slate-50 via-white to-blue-50 gap-4"
      >
        <div className="w-10 h-10 border-4 border-green-500 border-t-transparent
                        rounded-full animate-spin" />
        <p className="text-gray-400 text-sm">
          AI is generating your job recommendations...
        </p>
      </div>
    )
  }

  // ── Error ──
  if (error) {
    return (
      <div
        style={{ minHeight: 'calc(100vh - 57px)' }}
        className="flex flex-col items-center justify-center
                   bg-gradient-to-br from-slate-50 via-white to-blue-50 gap-4"
      >
        <span className="text-4xl">⚠️</span>
        <p className="text-gray-500 text-sm">{error}</p>
        <button
          onClick={() => navigate('/profile/build')}
          className="bg-blue-600 text-white px-6 py-2 rounded-xl text-sm
                     font-semibold hover:bg-blue-700 transition-all"
        >
          Complete Your Profile →
        </button>
      </div>
    )
  }

  return (
    <div
      style={{ minHeight: 'calc(100vh - 57px)' }}
      className="flex flex-col items-center bg-gradient-to-br
                 from-slate-50 via-white to-blue-50 px-4 py-10"
    >
      <div className="w-full max-w-5xl flex flex-col gap-6">

        {/* ── Header ── */}
        <div className="flex flex-col gap-1">
          <div className="flex items-center gap-2">
            <span className="text-2xl">🎯</span>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-gray-900">
              AI Job Recommendations
            </h1>
          </div>
          <p className="text-gray-400 text-sm ml-9">
            Personalized job matches generated by Gemini AI based on your profile.
          </p>
        </div>

        {/* ── AI Badge ── */}
        <div className="flex items-center justify-between flex-wrap gap-3">
          <div className="inline-flex items-center gap-2 bg-green-50 text-green-700
                          text-xs font-semibold px-4 py-2 rounded-full border
                          border-green-200">
            <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
            Powered by Gemini AI · {jobs.length} matches found
          </div>

          {/* Page indicator — top */}
          <span className="text-xs text-gray-400 font-medium">
            Showing {page * JOBS_PER_PAGE + 1}–{Math.min((page + 1) * JOBS_PER_PAGE, jobs.length)} of {jobs.length} jobs
          </span>
        </div>

        {/* ── Job Cards Grid ── */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
          {visibleJobs.map((job, index) => (
            <div
              key={index}
              className="bg-white rounded-2xl border border-gray-200 shadow-sm
                         hover:shadow-lg hover:-translate-y-1 transition-all
                         duration-300 p-5 flex flex-col gap-4"
            >
              {/* Top Row */}
              <div className="flex items-start justify-between gap-2">
                <div>
                  <h3 className="text-gray-900 font-bold text-sm leading-snug">
                    {job.title}
                  </h3>
                  <p className="text-gray-400 text-xs mt-0.5">{job.company}</p>
                </div>
                <span className={`shrink-0 text-xs font-semibold px-2.5 py-1
                                  rounded-full border
                  ${job.type === 'Internship'
                    ? 'bg-purple-50 text-purple-600 border-purple-200'
                    : 'bg-blue-50 text-blue-600 border-blue-200'}`}>
                  {job.type}
                </span>
              </div>

              {/* Meta Info */}
              <div className="flex flex-wrap gap-2 text-xs text-gray-500">
                <span>📍 {job.location}</span>
                <span>💰 {job.salary}</span>
              </div>

              {/* Match Reason */}
              <div className="bg-green-50 border border-green-100 rounded-xl p-3">
                <p className="text-xs text-green-700 font-semibold mb-1">
                  ✅ Why you match
                </p>
                <p className="text-xs text-green-600 leading-relaxed">
                  {job.matchReason}
                </p>
              </div>

              {/* Skills to Learn */}
              {job.skillsToLearn?.length > 0 && (
                <div>
                  <p className="text-xs text-gray-400 font-semibold mb-1.5">
                    📚 Skills to learn
                  </p>
                  <div className="flex flex-wrap gap-1.5">
                    {job.skillsToLearn.map((skill) => (
                      <span
                        key={skill}
                        className="bg-amber-50 text-amber-600 border border-amber-200
                                   text-xs font-medium px-2 py-0.5 rounded-full"
                      >
                        {skill}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {/* Apply Button */}
              <a
                href={job.applyLink}
                target="_blank"
                rel="noopener noreferrer"
                className="mt-auto w-full bg-blue-600 hover:bg-blue-700 text-white
                           text-xs font-bold py-2.5 rounded-xl text-center
                           transition-all active:scale-95"
              >
                Apply on LinkedIn →
              </a>
            </div>
          ))}
        </div>

        {/* ── Pagination Bar ── */}
        {totalPages > 1 && (
          <div className="flex items-center justify-center gap-4 pt-2">

            {/* Prev Button */}
            <button
              onClick={goPrev}
              disabled={page === 0}
              className={`flex items-center gap-1.5 px-4 py-2 rounded-xl text-sm
                          font-semibold border transition-all
                          ${page === 0
                            ? 'opacity-40 cursor-not-allowed bg-white border-gray-200 text-gray-400'
                            : 'bg-white border-gray-200 text-gray-700 hover:border-blue-400 hover:text-blue-600 hover:shadow-sm'
                          }`}
            >
              ← Previous
            </button>

            {/* Page Dots */}
            <div className="flex items-center gap-2">
              {Array.from({ length: totalPages }).map((_, i) => (
                <button
                  key={i}
                  onClick={() => {
                    setPage(i)
                    window.scrollTo({ top: 0, behavior: 'smooth' })
                  }}
                  className={`w-8 h-8 rounded-full text-xs font-bold border
                              transition-all
                    ${i === page
                      ? 'bg-blue-600 text-white border-blue-600 shadow-md'
                      : 'bg-white text-gray-400 border-gray-200 hover:border-blue-400 hover:text-blue-600'
                    }`}
                >
                  {i + 1}
                </button>
              ))}
            </div>

            {/* Next Button */}
            <button
              onClick={goNext}
              disabled={page === totalPages - 1}
              className={`flex items-center gap-1.5 px-4 py-2 rounded-xl text-sm
                          font-semibold border transition-all
                          ${page === totalPages - 1
                            ? 'opacity-40 cursor-not-allowed bg-white border-gray-200 text-gray-400'
                            : 'bg-white border-gray-200 text-gray-700 hover:border-blue-400 hover:text-blue-600 hover:shadow-sm'
                          }`}
            >
              Next →
            </button>
          </div>
        )}

        {/* ── Bottom Note ── */}
        <p className="text-center text-xs text-gray-300 mt-2">
          Recommendations are generated fresh based on your current profile.
          Update your profile to get better matches.
        </p>

      </div>
    </div>
  )
}

export default Jobs
